services:
  - type: web
    name: idchaha
    runtime: python
    plan: free
    buildCommand: cd react-app && npm install && npm run build
    startCommand: python server.py
    envVars:
      - key: HENRIK_API_KEYS
        sync: false
      - key: ALLOWED_HOSTS
        value: idchaha.lol,www.idchaha.lol
